/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class p_KategoriProduk extends javax.swing.JPanel {

    /**
     * Creates new form p_KategoriProduk
     */
    public p_KategoriProduk() {
        initComponents();
        reset();
        load_table_Kategori();
    }
    
     //method reset
    void reset(){
       t_idKategori.setText(null);
       t_namaKategori1.setText(null);
       //aktifkan pengeditan
       t_idKategori.setEditable(true);
    }
    
    //method load tabel guru
   void load_table_Kategori(){
       DefaultTableModel model = new DefaultTableModel();
       
       //menambahkan kolom ke dlm tabel
       model.addColumn("No.");
       model.addColumn("ID Kategori");
       model.addColumn("Nama Kategori");
       int no = 1;
       //Query SL utk mengambil semua data dari tabel
       String sql = "SELECT * FROM kategori";
       
       try {
           Connection con = koneksi.konek();
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery(sql);
           
           while (rs.next()) {
               //ambil data kolom id dan nama kategori
               String id_kategori = rs.getString("id_kategori");
               String nama_kategori = rs.getString("nama_kategori");
               //membuat array berisi data satu baris
               Object[] baris = {no++, id_kategori, nama_kategori, };
               //menambahkan array ke dlm tabel
               model.addRow(baris);
           }
       } catch (SQLException sQLException) {
           //menampilkan pesan error
           JOptionPane.showMessageDialog(null, "Gagal mengambil data!");
           System.out.println(sQLException);
       }
       table_katProduk.setModel(model);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        p_main = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        t_idKategori = new javax.swing.JTextField();
        b_tambah = new javax.swing.JButton();
        b_ubah = new javax.swing.JButton();
        b_hapus = new javax.swing.JButton();
        b_reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_katProduk = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        t_namaKategori1 = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1070, 633));

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 36)); // NOI18N
        jLabel1.setText("Kategori Produk");

        p_main.setBackground(new java.awt.Color(255, 255, 255));
        p_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p_main.setPreferredSize(new java.awt.Dimension(1106, 562));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nama Kategori : ");

        t_idKategori.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        t_idKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idKategoriActionPerformed(evt);
            }
        });

        b_tambah.setBackground(new java.awt.Color(51, 204, 0));
        b_tambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Plus+.png"))); // NOI18N
        b_tambah.setText("Tambah");
        b_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tambahActionPerformed(evt);
            }
        });

        b_ubah.setBackground(new java.awt.Color(255, 102, 0));
        b_ubah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Edit2.png"))); // NOI18N
        b_ubah.setText("Ubah");
        b_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ubahActionPerformed(evt);
            }
        });

        b_hapus.setBackground(new java.awt.Color(255, 51, 51));
        b_hapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        b_hapus.setText("Hapus");
        b_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hapusActionPerformed(evt);
            }
        });

        b_reset.setBackground(new java.awt.Color(0, 153, 255));
        b_reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/reset.png"))); // NOI18N
        b_reset.setText("Reset");
        b_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_resetActionPerformed(evt);
            }
        });

        table_katProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_katProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_katProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_katProduk);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Id Kategori       : ");

        t_namaKategori1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout p_mainLayout = new javax.swing.GroupLayout(p_main);
        p_main.setLayout(p_mainLayout);
        p_mainLayout.setHorizontalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mainLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_mainLayout.createSequentialGroup()
                        .addComponent(b_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(b_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(p_mainLayout.createSequentialGroup()
                        .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(p_mainLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(t_idKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(p_mainLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(t_namaKategori1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 409, Short.MAX_VALUE))))
        );
        p_mainLayout.setVerticalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mainLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t_idKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t_namaKategori1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_tambah)
                    .addComponent(b_ubah)
                    .addComponent(b_hapus)
                    .addComponent(b_reset))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_main, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_main, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tambahActionPerformed
         //ambil input dari textField kode dan nama jurusan 
        String id_kategori = t_idKategori.getText();
         String nama_kategori = t_namaKategori1.getText();
        
        //Query SQL
        try {
            String sql = "INSERT INTO kategori(id_kategori, nama_kategori) VALUES(?,?)";
            Connection con = koneksi.konek();//buat koneksi ke DB
            //siapkan query SQL utk dieksekusi
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, id_kategori);
            ps.setString(2, nama_kategori);          
            //jalankan query
            ps.execute();

            //tampilkan pesan bahwa data berhasil disimpan
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        } catch (SQLException sQLException) {
            //tampilkan pesan error jika gagal menyimpan
            JOptionPane.showMessageDialog(null, "Data gagal disimpan!");
            System.out.println(sQLException);
        } 
        load_table_Kategori();
        reset();
    }//GEN-LAST:event_b_tambahActionPerformed

    private void b_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ubahActionPerformed
         //ambil input dari textField kode dan nama jurusan
        String id_kategori = t_idKategori.getText();
        String nama_kategori = t_namaKategori1.getText();
        
        //Query SQL
        try {
            String sql = "UPDATE kategori SET nama_kategori=? WHERE id_kategori=?";
            Connection con = koneksi.konek();//buat koneksi ke DB
            //siapkan query SQL utk dieksekusi
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, nama_kategori);
            ps.setString(2, id_kategori);
            //jalankan query
            ps.execute();

            //tampilkan pesan bahwa data berhasil disimpan
            JOptionPane.showMessageDialog(null, "Data berhasil diubah");
        } catch (SQLException sQLException) {
            //tampilkan pesan error jika gagal menyimpan
            JOptionPane.showMessageDialog(null, "Data gagal diubah!");
            System.out.println(sQLException);
        } 
        load_table_Kategori();
        reset();
    }//GEN-LAST:event_b_ubahActionPerformed

    private void b_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hapusActionPerformed
       
        String id_kategori = t_idKategori.getText();
        
        //Query SQL
        try {
            String sql = "DELETE FROM kategori WHERE id_kategori=?";
            Connection con = koneksi.konek();//buat koneksi ke DB
            //siapkan query SQL utk dieksekusi
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, id_kategori);
            //jalankan query
            ps.execute();

            //tampilkan pesan bahwa data berhasil disimpan
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
        } catch (SQLException sQLException) {
            //tampilkan pesan error jika gagal menyimpan
            JOptionPane.showMessageDialog(null, "Data gagal dihapus!");
            System.out.println(sQLException);
        } 
        load_table_Kategori();
        reset();
    }//GEN-LAST:event_b_hapusActionPerformed

    private void b_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_resetActionPerformed
        reset();
    }//GEN-LAST:event_b_resetActionPerformed

    private void table_katProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_katProdukMouseClicked
        //ambil indeks baris yang di klik
        int barisDipilih = table_katProduk.rowAtPoint(evt.getPoint());
        
        //ambil nilai kolom kode dan nama jurusan
        String id_kategori =table_katProduk.getValueAt(barisDipilih, 1).toString();
        String nama_kategori = table_katProduk.getValueAt(barisDipilih, 2).toString();
        
        //tampilkan kode dan nama jurusaan ke textField 
        t_idKategori.setText(id_kategori);
        t_namaKategori1.setText(nama_kategori);
        //Nonaktifkan pengeditan pd textField id kategori
        t_idKategori.setEditable(false);
    }//GEN-LAST:event_table_katProdukMouseClicked

    private void t_idKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idKategoriActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_hapus;
    private javax.swing.JButton b_reset;
    private javax.swing.JButton b_tambah;
    private javax.swing.JButton b_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel p_main;
    private javax.swing.JTextField t_idKategori;
    private javax.swing.JTextField t_namaKategori1;
    private javax.swing.JTable table_katProduk;
    // End of variables declaration//GEN-END:variables
}
