/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pongo
 */
public class p_kategoriuser extends javax.swing.JPanel {
    ArrayList<String[]> dataUser = new ArrayList<>();
    
    public p_kategoriuser() {
        initComponents();
        load_table_user();
    }
    
    void load_table_user(){
         DefaultTableModel model = new DefaultTableModel();
       
       //menambahkan kolom ke dlm tabel
      model.addColumn("No");
       model.addColumn("ID User");
       model.addColumn("Nama User"); 
       model.addColumn("Alamat"); 
       model.addColumn("No HP"); 
       model.addColumn("role");
       
       dataUser.clear();//mengosongkan list agar tidak duplikat
       int no = 1; 
       //Query SL utk mengambil semua data dari tabel
       String sql = "SELECT * FROM user";
       
       try {
           Connection con = koneksi.konek();//membuka koneksi ke DB
           //membut Statement utk menjalankan query SQL
           Statement st = con.createStatement();
           //menjalankan query
           ResultSet rs = st.executeQuery(sql);
          
           //melakukan iterasi utk setiap baris data
           while (rs.next()) {
               
               
               //simpan data user 
               String [] data = {
                   rs.getString("id_user"),
                   rs.getString("nama_user"),
                   rs.getString("alamat"),
                   rs.getString("no_hp"),
                   rs.getString("role"),
                   rs.getString("password")
               };
               dataUser.add(data);
               //membuat array berisi data satu baris
               Object[] baris = {
               no++,data[0], data[1], data[2], data[3], data[4]};
               //menambahkan array ke dlm tabel
               model.addRow(baris);
           }
       } catch (SQLException sQLException) {
           //menampilkan pesan error
           JOptionPane.showMessageDialog(null, "Gagal mengambil data!");
           System.out.println(sQLException);
       }
       table_dataKaryawan.setModel(model);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_dasar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        p_main = new javax.swing.JPanel();
        b_tambah = new javax.swing.JButton();
        t_cariKaryawan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_dataKaryawan = new javax.swing.JTable();

        p_dasar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 36)); // NOI18N
        jLabel1.setText("Kategori User ");

        p_main.setBackground(new java.awt.Color(255, 255, 255));
        p_main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        b_tambah.setBackground(new java.awt.Color(51, 204, 0));
        b_tambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Plus+.png"))); // NOI18N
        b_tambah.setText("Tambah");
        b_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tambahActionPerformed(evt);
            }
        });

        t_cariKaryawan.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cari Nama Karyawan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        table_dataKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        table_dataKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_dataKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_dataKaryawan);

        javax.swing.GroupLayout p_mainLayout = new javax.swing.GroupLayout(p_main);
        p_main.setLayout(p_mainLayout);
        p_mainLayout.setHorizontalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mainLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_mainLayout.createSequentialGroup()
                        .addComponent(b_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(t_cariKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(325, Short.MAX_VALUE))
        );
        p_mainLayout.setVerticalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mainLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_tambah)
                    .addComponent(t_cariKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout p_dasarLayout = new javax.swing.GroupLayout(p_dasar);
        p_dasar.setLayout(p_dasarLayout);
        p_dasarLayout.setHorizontalGroup(
            p_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_dasarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(p_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        p_dasarLayout.setVerticalGroup(
            p_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_dasarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_dasar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_dasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tambahActionPerformed
        //buat objek panel edit
        p_editDataKaryawan panelBaru = new p_editDataKaryawan();
         // Sembunyikan tombol ubah di dalam panel edit
        panelBaru.tambahUser();
        //tampil ke panel dasar
        panelBaru.setSize(p_dasar.getSize());
        panelBaru.setVisible(true);

        p_dasar.setLayout(new BorderLayout());
        p_dasar.setVisible(false);
        p_dasar.removeAll();
        p_dasar.add(panelBaru, BorderLayout.CENTER);
        p_dasar.repaint();
        p_dasar.revalidate();
        p_dasar.setVisible(true);
    }//GEN-LAST:event_b_tambahActionPerformed

    private void table_dataKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_dataKaryawanMouseClicked
        int barisdipilih = table_dataKaryawan.rowAtPoint(evt.getPoint());
        
        if (barisdipilih >= 0) {
            String id = table_dataKaryawan.getValueAt(barisdipilih, 1).toString();
            String nama = table_dataKaryawan.getValueAt(barisdipilih, 2).toString();
            String alamat = table_dataKaryawan.getValueAt(barisdipilih, 3).toString();
            String noHP = table_dataKaryawan.getValueAt(barisdipilih, 4).toString();
            String role = table_dataKaryawan.getValueAt(barisdipilih, 5).toString();
            
            
            p_editDataKaryawan panelEdit = new p_editDataKaryawan();
            panelEdit.tampildata(id, nama, alamat, noHP, role);
            panelEdit.ubahUser();// tombol ubah tampil, tombol simpan disembunyikan

            //tampilkan ke p_dasar
           panelEdit.setSize(p_dasar.getSize());
            panelEdit.setVisible(true);

            p_dasar.removeAll();
            p_dasar.setLayout(new BorderLayout());
            p_dasar.add(panelEdit, BorderLayout.CENTER);
            p_dasar.revalidate();
            p_dasar.repaint();
            
        }
    }//GEN-LAST:event_table_dataKaryawanMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel p_dasar;
    private javax.swing.JPanel p_main;
    private javax.swing.JTextField t_cariKaryawan;
    private javax.swing.JTable table_dataKaryawan;
    // End of variables declaration//GEN-END:variables
}
